version: "3.4"
services:
  pgweb:
    image: sosedoff/pgweb
    expose:
      - 8081
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/sparrow?sslmode=disable
    depends_on:
      - db
